version: '3.4'

# https://code.visualstudio.com/docs/containers/docker-compose

services:

  session:
    extends:
      file: ./session/compose-session-dev.yml
      service: session
    networks:
      - my_network

  manager:
    extends:
      file: ./session-manager/compose-manager-dev.yml
      service: manager
    networks:
      - my_network

networks:
  my_network:
    driver: bridge