# BUILD
# docker compose -f compose-manager-dev.yml up --build
# ATTACH
# select 'manager attach' and run
services:
  manager:
    container_name: manager-dev
    build:
      context: .
      dockerfile: dockerfile-dev
    image: manager-dev:latest
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 8080:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 --nolazy ./.dist/session-manager.js

# docker run --rm --name manager-dev -p 9229:9229 -v .:/app manager-dev node --inspect=0.0.0.0:9229 --nolazy ./.dist/session-manager.js


