# BUILD
# docker compose -f compose-session-dev.yml up --build
# ATTACH
# select 'manager attach' and run
services:
  session:
    container_name: session-dev
    build:
      context: .
      dockerfile: dockerfile-dev
    image: session-dev:latest
    volumes:
      - .:/app

    ports:
      - 9230:9229
    command: node --inspect=0.0.0.0:9229 --nolazy ./.dist/session.js

# docker run --rm --name session-dev -p 9230:9229 -v .:/app session-dev node --inspect=0.0.0.0:9229 --nolazy ./.dist/session.js
